package CeoGUI;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */



import ManagerGUI.*;
import dbdriver.DBDriver;
import dboperation.HomeCompanyDBOperation;
import dboperation.PurchaseDBOperation;
import dboperation.SaleDBOperation;

import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Dimension;
/**
 *
 * @author welcome
 */import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.HashSet;
import java.util.Locale;
import javax.swing.BorderFactory;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.border.TitledBorder;
//import org.jfree.chart.ChartFactory;
//import org.jfree.chart.ChartPanel;
//import org.jfree.chart.JFreeChart;
//import org.jfree.chart.plot.PlotOrientation;
//import org.jfree.data.category.DefaultCategoryDataset;

public class CEOOperationFrame extends javax.swing.JFrame {

    /**
     * Creates new form OperationFrame
     */
    public CEOOperationFrame() {
        
        
        super("CEO OPERATION FRAME Login By"+" "+LoginFrame.uname);
        initComponents();
        
       
       
       
        

       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem15 = new javax.swing.JMenuItem();
        jMenu6 = new javax.swing.JMenu();
        jMenuItem12 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        getContentPane().setLayout(null);

        jMenuBar2.setBackground(new java.awt.Color(255, 255, 255));
        jMenuBar2.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jMenuBar2.setPreferredSize(new java.awt.Dimension(479, 50));

        jMenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/editicon.png"))); // NOI18N
        jMenu1.setText("Edit Profile");
        jMenu1.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N

        jMenuItem7.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jMenuItem7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/editadmin.png"))); // NOI18N
        jMenuItem7.setText("Change Password");
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem7);

        jMenuBar2.add(jMenu1);

        jMenu2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/manageitem.png"))); // NOI18N
        jMenu2.setText(" Report");
        jMenu2.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N

        jMenuItem1.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jMenuItem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/sale.png"))); // NOI18N
        jMenuItem1.setText("View Sale Report");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem1);

        jMenuItem15.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jMenuItem15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/purchase.png"))); // NOI18N
        jMenuItem15.setText("View Purchase Report");
        jMenuItem15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem15ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem15);

        jMenuBar2.add(jMenu2);

        jMenu6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/logout.png"))); // NOI18N
        jMenu6.setText("Logout");
        jMenu6.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N

        jMenuItem12.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jMenuItem12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/exit.png"))); // NOI18N
        jMenuItem12.setText("Exit");
        jMenuItem12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem12ActionPerformed(evt);
            }
        });
        jMenu6.add(jMenuItem12);

        jMenuBar2.add(jMenu6);

        setJMenuBar(jMenuBar2);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
        // TODO add your handling code here:

        this.dispose();
        Dimension d=Toolkit.getDefaultToolkit().getScreenSize();
        CEOEditFrame nf=new CEOEditFrame();
        nf.setVisible(true);
        nf.setSize(d);
    }//GEN-LAST:event_jMenuItem7ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        
        ArrayList saleinfo=new SaleDBOperation().getAllSaleItemInfo();
        
        System.out.println("Saleinfo: "+saleinfo);
        
        ArrayList item=new ArrayList();
        
        for (int i = 0; i <saleinfo.size(); i++) 
        {
            ArrayList temp=(ArrayList) saleinfo.get(i);    
            item.add(temp.get(0));
        }
        
        HashSet hs=new HashSet();
        hs.addAll(item);
        item.clear();
        item.addAll(hs);
        
        ArrayList salebar=new ArrayList();
        
        for (int i = 0; i <item.size();i++) 
        {
            ArrayList temp1=new ArrayList();
            String itemname1=(String) item.get(i);
            
            int itemcost=0;
            
            for (int j = 0; j <saleinfo.size(); j++) 
            {
                ArrayList temp=(ArrayList) saleinfo.get(j);   
                String itemname2=(String) temp.get(0);
                
                if(itemname1.equals(itemname2))
                {
                    String str=(String) temp.get(1);
                    
                    System.out.println("str: "+str);
                    double cost=Double.parseDouble(str);
                  
                          int amount=(int)cost;
//                    System.out.println("cost: "+amount);
                    itemcost=itemcost+amount;
                }
                
            }
            
            temp1.add(itemname1);
            temp1.add(Integer.toString(itemcost));
            salebar.add(temp1);
        }
        SaleChartApplet.mas= new ArrayList();
        for (int i = 0; i <salebar.size(); i++) 
        {
            ArrayList temp=(ArrayList) salebar.get(i);
            System.out.println("temp: "+temp);
             SaleChartApplet.mas.add(temp);
        }
        
        SaleChartApplet.message="Sale Graph";
       
        
        new SaleGraphChart().intiateSimulation();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem15ActionPerformed
        // TODO add your handling code here:
        ArrayList purchaseinfo=new PurchaseDBOperation().getAllPurcaseItemInfo();
        
        System.out.println("purchaseinfo: "+purchaseinfo);
        
        ArrayList item=new ArrayList();
        
        for (int i = 0; i <purchaseinfo.size(); i++) 
        {
            ArrayList temp=(ArrayList) purchaseinfo.get(i);    
            item.add(temp.get(0));
        }
        
        HashSet hs=new HashSet();
        hs.addAll(item);
        item.clear();
        item.addAll(hs);
        
        ArrayList salebar=new ArrayList();
        
        for (int i = 0; i <item.size();i++) 
        {
            ArrayList temp1=new ArrayList();
            String itemname1=(String) item.get(i);
            
            int itemcost=0;
            
            for (int j = 0; j <purchaseinfo.size(); j++) 
            {
                ArrayList temp=(ArrayList) purchaseinfo.get(j);   
                String itemname2=(String) temp.get(0);
                
                if(itemname1.equals(itemname2))
                {
                    String str=(String) temp.get(1);
                    
                    System.out.println("str: "+str);
                    double cost=Double.parseDouble(str);
                  
                          int amount=(int)cost;
//                    System.out.println("cost: "+amount);
                    itemcost=itemcost+amount;
                }
                
            }
            
            temp1.add(itemname1);
            temp1.add(Integer.toString(itemcost));
            salebar.add(temp1);
        }
        PurchaseChartApplet.mas=new ArrayList();
        for (int i = 0; i <salebar.size(); i++) 
        {
            ArrayList temp=(ArrayList) salebar.get(i);
            System.out.println("temp: "+temp);
             PurchaseChartApplet.mas.add(temp);
        }
        
        PurchaseChartApplet.message="Purchase Graph";
       
        
        new PurchaseGraphChart().intiateSimulation();
        
    }//GEN-LAST:event_jMenuItem15ActionPerformed

    private void jMenuItem12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem12ActionPerformed
        // TODO add your handling code here:
        this.dispose();
        Dimension d = Toolkit.getDefaultToolkit().getScreenSize();
        LoginFrame af = new LoginFrame();
        af.setVisible(true);
        af.setSize(d);
    }//GEN-LAST:event_jMenuItem12ActionPerformed

    
    
    public boolean isHomeCompanyAdded()
    {
        boolean flag=false;
        
         try
        {

             Statement st= new DBDriver().getStatment();
             String query="Select * from homecompanyinfo ";
             ResultSet rs=st.executeQuery(query);
            
            if(rs.next())
            {
             flag=true;   
            }
            
           
          
            st.close();
        }

        catch(Exception e)
        {
            System.out.println("Exeption in isHomeCompanyAdded() of OperationFrame: "+e);
            flag=false;
        }
        
        
        return flag;
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CEOOperationFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CEOOperationFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CEOOperationFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CEOOperationFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CEOOperationFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem12;
    private javax.swing.JMenuItem jMenuItem15;
    private javax.swing.JMenuItem jMenuItem7;
    // End of variables declaration//GEN-END:variables
}
