/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package staffGUI;
import ManagerGUI.CurrentDateTime;
import SearchOperation.HSNSACCodeList;


import dboperation.ManageItemDBOperation;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import ManagerGUI.LoginFrame;
import dboperation.ManageProfileDBOperation;

/**
 *
 * @author welcome
 */
public class EditItemFrame extends javax.swing.JFrame {
   public static String sname="";
   public static String logoutdatetime=new CurrentDateTime().getDateTime();

    /**
     * Creates new form AddItemFrame
     */
    public EditItemFrame() {
        
        super ("EDIT ITEM Login By"+" "+LoginFrame.uname);
        initComponents();
        
            ManageItemDBOperation mi=new ManageItemDBOperation();
           // sname=sname.toLowerCase();
            ArrayList iteminfo=mi.getItemInfo(sname);
        //    System.out.println(iteminfo);
            
            String type=(String) iteminfo.get(0);
            
            if(type.equals("Goods"))
            {
                String str1=(String) iteminfo.get(3);
            String []st1=str1.split(":");
            
            String str2=(String) iteminfo.get(4);
            String []st2=str2.split(":");
            
            jTextField1.setText((String) iteminfo.get(1));
            
            jRadioButton1.setSelected(true);
            jTextArea1.setText((String) iteminfo.get(2));
            jComboBox2.setSelectedItem(st1[1]);
            jComboBox3.setSelectedItem(st2[1]);
            jTextField5.setText(st1[0]);
            jLabel9.setText(st1[1]);
            jTextField6.setText(st2[0]);
            jLabel10.setText(st2[1]);
            jTextField4.setText((String) iteminfo.get(5));
            jComboBox1.setSelectedItem(iteminfo.get(6));
            jTextField5.setEditable(false);
            jTextField5.setBackground(Color.lightGray);
                  
            }
            
             if(type.equals("Service"))
            {              
            
            jTextField1.setText((String) iteminfo.get(1));
            
            jRadioButton2.setSelected(true);
            jTextArea1.setText((String) iteminfo.get(2));
            jComboBox2.setSelectedItem((String) iteminfo.get(3));
            jComboBox3.setEnabled(false);
            jTextField5.setEditable(false);
            jLabel9.setEnabled(false);
            jTextField6.setEditable(false);
            jLabel10.setEnabled(false);
            jTextField4.setText((String) iteminfo.get(5));
            jComboBox1.setSelectedItem(iteminfo.get(6));
           
        
                
            }
            
            
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jLabel7 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jComboBox2 = new javax.swing.JComboBox();
        jComboBox3 = new javax.swing.JComboBox();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenuItem10 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem15 = new javax.swing.JMenuItem();
        jMenuItem9 = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        jMenuItem11 = new javax.swing.JMenuItem();
        jMenuItem16 = new javax.swing.JMenuItem();
        jMenuItem17 = new javax.swing.JMenuItem();
        jMenuItem18 = new javax.swing.JMenuItem();
        jMenu7 = new javax.swing.JMenu();
        jMenuItem19 = new javax.swing.JMenuItem();
        jMenuItem20 = new javax.swing.JMenuItem();
        jMenu6 = new javax.swing.JMenu();
        jMenuItem12 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);

        jPanel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.setPreferredSize(new java.awt.Dimension(680, 589));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel1.setText("Item Name:");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(13, 29, 87, 23);

        jTextField1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(jTextField1);
        jTextField1.setBounds(211, 33, 450, 30);

        jLabel2.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel2.setText("Product Description:");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(13, 124, 149, 23);

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jTextArea1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jTextArea1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextArea1KeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(jTextArea1);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(211, 124, 450, 96);

        jLabel3.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel3.setText("Unit 2:");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(420, 240, 49, 23);

        jLabel4.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel4.setText("HSN/SAC Code:");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(13, 323, 113, 23);

        jLabel5.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel5.setText("GST Rate:");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(13, 364, 71, 23);

        jTextField4.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(jTextField4);
        jTextField4.setBounds(211, 325, 168, 25);

        jLabel6.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel6.setText(" Type:");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(10, 72, 44, 23);

        jRadioButton1.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jRadioButton1.setText("Goods");
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });
        jRadioButton1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jRadioButton1KeyPressed(evt);
            }
        });
        jPanel1.add(jRadioButton1);
        jRadioButton1.setBounds(211, 75, 73, 31);

        jRadioButton2.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jRadioButton2.setText("Service");
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });
        jRadioButton2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jRadioButton2KeyPressed(evt);
            }
        });
        jPanel1.add(jRadioButton2);
        jRadioButton2.setBounds(348, 75, 77, 31);

        jLabel7.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel7.setText("Unit 1:");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(13, 237, 49, 23);

        jComboBox1.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select", "0%", "5%", "12%", "18%", "28%" }));
        jComboBox1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jComboBox1KeyPressed(evt);
            }
        });
        jPanel1.add(jComboBox1);
        jComboBox1.setBounds(211, 366, 168, 25);

        jLabel8.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel8.setText("Conversion Rate:");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(13, 282, 125, 23);

        jTextField5.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(jTextField5);
        jTextField5.setBounds(211, 284, 35, 25);

        jTextField6.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(jTextField6);
        jTextField6.setBounds(350, 284, 59, 25);

        jButton1.setBackground(new java.awt.Color(0, 51, 102));
        jButton1.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/save.png"))); // NOI18N
        jButton1.setText("Save");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jButton1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButton1KeyPressed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(255, 450, 100, 35);

        jComboBox2.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "None", "Bags", "Bale", "Bundles", "Buckles", "Billions of units", "Box", "Bottles", "Bunches", "Cans", "Cubic meter", "Cubic centimeter", "Centimeter", "Cartons", "Dozen", "Drum", "Great gross", "Grams", "Gross", "Gross yards", "Kilograms", "Kiloliter", "Kilometre", "Millilitre", "Meters", "Numbers", "Packs", "Pieces", "Pairs", "Quintal", "Rolls", "Sets", "Square feet", "Square meters", "Square yards", "Tablets", "Ten gross", "Thousands", "Tonnes", "Tubes", "Us gallons", "Units", "Yards", "Others", " " }));
        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });
        jComboBox2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jComboBox2KeyPressed(evt);
            }
        });
        jPanel1.add(jComboBox2);
        jComboBox2.setBounds(211, 237, 168, 25);

        jComboBox3.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "None", "Bags", "Bale", "Bundles", "Buckles", "Billions of units", "Box", "Bottles", "Bunches", "Cans", "Cubic meter", "Cubic centimeter", "Centimeter", "Cartons", "Dozen", "Drum", "Great gross", "Grams", "Gross", "Gross yards", "Kilograms", "Kiloliter", "Kilometre", "Millilitre", "Meters", "Numbers", "Packs", "Pieces", "Pairs", "Quintal", "Rolls", "Sets", "Square feet", "Square meters", "Square yards", "Tablets", "Ten gross", "Thousands", "Tonnes", "Tubes", "Us gallons", "Units", "Yards", "Others", " " }));
        jComboBox3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jComboBox3KeyPressed(evt);
            }
        });
        jPanel1.add(jComboBox3);
        jComboBox3.setBounds(490, 237, 168, 25);

        jLabel9.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel9.setText("Unit1");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(250, 290, 90, 17);

        jLabel10.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel10.setText("Unit2");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(415, 290, 90, 17);

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/searchicon.png"))); // NOI18N
        jLabel13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel13MouseClicked(evt);
            }
        });
        jLabel13.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jLabel13KeyPressed(evt);
            }
        });
        jPanel1.add(jLabel13);
        jLabel13.setBounds(382, 325, 35, 25);

        jMenuBar1.setBackground(new java.awt.Color(255, 255, 255));
        jMenuBar1.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jMenuBar1.setPreferredSize(new java.awt.Dimension(479, 50));

        jMenu4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/manageparty.png"))); // NOI18N
        jMenu4.setText("Manage Client");
        jMenu4.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N

        jMenuItem8.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jMenuItem8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/addcompany.png"))); // NOI18N
        jMenuItem8.setText("Add Client");
        jMenuItem8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem8ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem8);

        jMenuItem10.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jMenuItem10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/editcompany.png"))); // NOI18N
        jMenuItem10.setText("Edit / Search Client");
        jMenuItem10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem10ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem10);

        jMenuBar1.add(jMenu4);

        jMenu2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/manageitem.png"))); // NOI18N
        jMenu2.setText("Manage Item");
        jMenu2.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N

        jMenuItem1.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jMenuItem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/addcompany.png"))); // NOI18N
        jMenuItem1.setText("Add Item");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem1);

        jMenuItem15.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jMenuItem15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/editcompany.png"))); // NOI18N
        jMenuItem15.setText("Edit / Search Item");
        jMenuItem15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem15ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem15);

        jMenuItem9.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jMenuItem9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/stock.png"))); // NOI18N
        jMenuItem9.setText("Stock Register");
        jMenuItem9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem9ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem9);

        jMenuBar1.add(jMenu2);

        jMenu5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/purchase.png"))); // NOI18N
        jMenu5.setText("Purchase");
        jMenu5.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N

        jMenuItem11.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jMenuItem11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/new.png"))); // NOI18N
        jMenuItem11.setText("New Purchase");
        jMenuItem11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem11ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem11);

        jMenuItem16.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jMenuItem16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/search.png"))); // NOI18N
        jMenuItem16.setText("Search Purchase");
        jMenuItem16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem16ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem16);

        jMenuItem17.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jMenuItem17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/purchasepayment.png"))); // NOI18N
        jMenuItem17.setText("Purchase Payment");
        jMenuItem17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem17ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem17);

        jMenuItem18.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jMenuItem18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/advancepayment.png"))); // NOI18N
        jMenuItem18.setText("Advance Payment");
        jMenuItem18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem18ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem18);

        jMenuBar1.add(jMenu5);

        jMenu7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/sale.png"))); // NOI18N
        jMenu7.setText("Sale");
        jMenu7.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N

        jMenuItem19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/new.png"))); // NOI18N
        jMenuItem19.setText("New Sale");
        jMenuItem19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem19ActionPerformed(evt);
            }
        });
        jMenu7.add(jMenuItem19);

        jMenuItem20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/search.png"))); // NOI18N
        jMenuItem20.setText("Search Sale");
        jMenuItem20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem20ActionPerformed(evt);
            }
        });
        jMenu7.add(jMenuItem20);

        jMenuBar1.add(jMenu7);

        jMenu6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/logout.png"))); // NOI18N
        jMenu6.setText("Logout");
        jMenu6.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N

        jMenuItem12.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jMenuItem12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/exit.png"))); // NOI18N
        jMenuItem12.setText("Exit");
        jMenuItem12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem12ActionPerformed(evt);
            }
        });
        jMenu6.add(jMenuItem12);

        jMenuBar1.add(jMenu6);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(342, 342, 342)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 707, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(328, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 512, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(264, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String type = "";
        String itemname = jTextField1.getText();
        String idescription = jTextArea1.getText();
        String unitx = (String) jComboBox2.getSelectedItem();
        String unity = (String) jComboBox3.getSelectedItem();
        String unit1 = 1 + ":" + unitx;
        String unit2 = jTextField6.getText() + ":" + unity;
        String hsnsac = jTextField4.getText();
        String gstrate = (String) jComboBox1.getSelectedItem();

        if (jRadioButton1.isSelected()) 
        {
            type = jRadioButton1.getText();
        } else if (jRadioButton2.isSelected())
        {
            type = jRadioButton2.getText();
            
        }
        
        if (itemname.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Item Name Cannot be Empty");

        } else if (jRadioButton1.isSelected()&&unitx.equals("None")) {
            JOptionPane.showMessageDialog(null, "Please Select Unit1");
        }  else if (hsnsac.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Please Select HSN/SAC Code");
        } else if (gstrate.equals("Select")) {
            JOptionPane.showMessageDialog(null, "Please Select GST Rate");
        } 
         else if(type.equals("Service") && !hsnsac.startsWith("99"))
        {
             JOptionPane.showMessageDialog(null, "HSN/SAC Code should start with 99");
        }
          else if(hsnsac.length()>8)
        {
            JOptionPane.showMessageDialog(null, "HSN/SAC Code should be within 8 characters");
        }
        
        else {
            ManageItemDBOperation md = new ManageItemDBOperation();
            if (md.updateIteminfo(type, sname, idescription, unit1, unit2, hsnsac, gstrate)) {
                JOptionPane.showMessageDialog(null, "Item Information Updated Successfully");
                 jRadioButton1.setSelected(false);
                jRadioButton2.setSelected(false);
                jTextField1.setText("");
                jTextArea1.setText("");
                jComboBox2.setSelectedItem("None");
                jComboBox3.setSelectedItem("None");
                jLabel9.setText("Unit1");
                jLabel10.setText("Unit2");
                jTextField5.setText("");
                jTextField4.setText("");
                jTextField6.setText("");
                jComboBox1.setSelectedItem("Select");
                

            } else {
                JOptionPane.showMessageDialog(null, "Oops There is Some Error Please Try Again");
            }

//            System.out.println("Type: "+type);
//            System.out.println("Item Name: "+itemname);
//            System.out.println("Product Description: "+idescription);
//            System.out.println("Unit1: "+unit1);
//            System.out.println("Unit2: "+unit2);
//            System.out.println("HSN/SAC: "+hsnsac);
//            System.out.println("GST Rate: "+gstrate);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        // TODO add your handling code here:
        jRadioButton1.setSelected(true);
        jRadioButton2.setSelected(false);
         jTextField5.setEnabled(true);
         jTextField5.setText("1");
         
        jTextField6.setEnabled(true);
         jLabel9.setEnabled(true);
          jLabel10.setEnabled(true);
           jComboBox2.setSelectedIndex(0);
           jComboBox3.setSelectedIndex(0);
               jComboBox2.setEnabled(true);
                   jComboBox3.setEnabled(true);
                   
                    jLabel9.setText("Unit1");
         jLabel10.setText("Unit2");
                   
           
        
        
        
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed
        // TODO add your handling code here:
       jRadioButton1.setSelected(false);
        jRadioButton2.setSelected(true);
        
        jComboBox2.setSelectedItem("Others");
        jComboBox3.setEnabled(false);
      
        jLabel9.setEnabled(false);
        jLabel10.setEnabled(false);
          jTextField5.setEnabled(false);
        jTextField6.setEnabled(false);
        jTextField5.setText("");
                jTextField6.setText("");
    }//GEN-LAST:event_jRadioButton2ActionPerformed

    private void jButton1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButton1KeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==KeyEvent.VK_ENTER)
        {
        String type = "";
        String itemname = jTextField1.getText();
        String idescription = jTextArea1.getText();
        String unitx = (String) jComboBox2.getSelectedItem();
        String unity = (String) jComboBox3.getSelectedItem();
        String unit1 = 1 + ":" + unitx;
        String unit2 = jTextField6.getText() + ":" + unity;
        String hsnsac = jTextField4.getText();
        String gstrate = (String) jComboBox1.getSelectedItem();

        if (jRadioButton1.isSelected()) 
        {
            type = jRadioButton1.getText();
        } else if (jRadioButton2.isSelected())
        {
            type = jRadioButton2.getText();
            
        }
        
        if (itemname.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Item Name Cannot be Empty");

        } else if (jRadioButton1.isSelected()&&unitx.equals("None")) {
            JOptionPane.showMessageDialog(null, "Please Select Unit1");
        }  else if (hsnsac.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Please Select HSN/SAC Code");
        } else if (gstrate.equals("Select")) {
            JOptionPane.showMessageDialog(null, "Please Select GST Rate");
        } else {
            ManageItemDBOperation md = new ManageItemDBOperation();
            if (md.updateIteminfo(type, sname, idescription, unit1, unit2, hsnsac, gstrate)) {
                JOptionPane.showMessageDialog(null, "Item Information Updated Successfully");
                 jRadioButton1.setSelected(false);
                jRadioButton2.setSelected(false);
                jTextField1.setText("");
                jTextArea1.setText("");
                jComboBox2.setSelectedItem("None");
                jComboBox3.setSelectedItem("None");
                jLabel9.setText("Unit1");
                jLabel10.setText("Unit2");
                jTextField5.setText("");
                jTextField4.setText("");
                jTextField6.setText("");
                jComboBox1.setSelectedItem("Select");
                

            } else {
                JOptionPane.showMessageDialog(null, "Oops There is Some Error Please Try Again");
            }

//            System.out.println("Type: "+type);
//            System.out.println("Item Name: "+itemname);
//            System.out.println("Product Description: "+idescription);
//            System.out.println("Unit1: "+unit1);
//            System.out.println("Unit2: "+unit2);
//            System.out.println("HSN/SAC: "+hsnsac);
//            System.out.println("GST Rate: "+gstrate);
        }
        }
    }//GEN-LAST:event_jButton1KeyPressed

    private void jTextArea1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextArea1KeyPressed
        // TODO add your handling code here:
         if(evt.getKeyCode()==KeyEvent.VK_TAB)
        {
            if (evt.getModifiers() > 0) {
                        jTextArea1.transferFocusBackward();
                    } else {
                        jTextArea1.transferFocus();
                    }
                    evt.consume();
        }
    }//GEN-LAST:event_jTextArea1KeyPressed

    private void jComboBox2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jComboBox2KeyPressed
        // TODO add your handling code here:
         jComboBox2.showPopup();
         String text=(String) jComboBox2.getSelectedItem();
        if (evt.getKeyCode() == KeyEvent.VK_ENTER)
        {
            jComboBox2.setSelectedItem(text);
        }
      
        String unit = (String) jComboBox2.getSelectedItem();

    //    System.out.println(unit);
        jLabel9.setText(unit);
    }//GEN-LAST:event_jComboBox2KeyPressed

    private void jComboBox3KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jComboBox3KeyPressed
        // TODO add your handling code here:
         jComboBox3.showPopup();
         String text=(String) jComboBox3.getSelectedItem();
        if (evt.getKeyCode() == KeyEvent.VK_ENTER)
        {
            jComboBox3.setSelectedItem(text);
        }
      
        String unit = (String) jComboBox3.getSelectedItem();

    //    System.out.println(unit);
        jLabel9.setText(unit);
    }//GEN-LAST:event_jComboBox3KeyPressed

    private void jComboBox1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jComboBox1KeyPressed
        // TODO add your handling code here:
        jComboBox1.showPopup();
         String text=(String) jComboBox1.getSelectedItem();
        if (evt.getKeyCode() == KeyEvent.VK_ENTER)
        {
            jComboBox1.setSelectedItem(text);
        }
    }//GEN-LAST:event_jComboBox1KeyPressed

    private void jRadioButton1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jRadioButton1KeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==KeyEvent.VK_ENTER)
        {
        jRadioButton1.setSelected(true);
        jRadioButton2.setSelected(false);
        }
    }//GEN-LAST:event_jRadioButton1KeyPressed

    private void jRadioButton2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jRadioButton2KeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==KeyEvent.VK_ENTER)
        {
        jRadioButton1.setSelected(false);
        jRadioButton2.setSelected(true);
        }
    }//GEN-LAST:event_jRadioButton2KeyPressed

    private void jLabel13MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel13MouseClicked
        // TODO add your handling code here:

        if(jRadioButton1.isSelected())
        {
            HSNSACCodeList.tablename = "hsngoodlist";
            Dimension d = Toolkit.getDefaultToolkit().getScreenSize();
            HSNSACCodeList hs = new HSNSACCodeList();
            hs.setSize(d);
            hs.revalidate();
            hs.setVisible(true);

        }
        else if(jRadioButton2.isSelected())
        {
            HSNSACCodeList.tablename = "hsnservicelist";
            Dimension d = Toolkit.getDefaultToolkit().getScreenSize();
            HSNSACCodeList hs = new HSNSACCodeList();
            hs.setSize(d);
            hs.revalidate();
            hs.setVisible(true);

        }

    }//GEN-LAST:event_jLabel13MouseClicked

    private void jLabel13KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jLabel13KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel13KeyPressed

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
        // TODO add your handling code here:
         String unit = (String) jComboBox2.getSelectedItem();

     //   System.out.println(unit);
        jLabel9.setText(unit);

    }//GEN-LAST:event_jComboBox2ActionPerformed

    private void jMenuItem8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem8ActionPerformed
        // TODO add your handling code here:

        this.dispose();
        Dimension d=Toolkit.getDefaultToolkit().getScreenSize();

        AddClientFrame af=new AddClientFrame();
        af.setVisible(true);
        af.setSize(d);
    }//GEN-LAST:event_jMenuItem8ActionPerformed

    private void jMenuItem10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem10ActionPerformed
        // TODO add your handling code here:

        this.dispose();
        Dimension d=Toolkit.getDefaultToolkit().getScreenSize();

        SearchRegisterPartyFrame sf=new SearchRegisterPartyFrame();
        sf.setVisible(true);
        sf.setSize(d);
    }//GEN-LAST:event_jMenuItem10ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:

        this.dispose();
        Dimension d=Toolkit.getDefaultToolkit().getScreenSize();

        AddItemFrame lf=new AddItemFrame();
        lf.setVisible(true);
        lf.setSize(d);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem15ActionPerformed
        // TODO add your handling code here:

        this.dispose();
        Dimension d=Toolkit.getDefaultToolkit().getScreenSize();

        SearchItemFrame lf=new SearchItemFrame();
        lf.setVisible(true);
        lf.setSize(d);
    }//GEN-LAST:event_jMenuItem15ActionPerformed

    private void jMenuItem9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem9ActionPerformed
        // TODO add your handling code here:
        this.dispose();
        Dimension d=Toolkit.getDefaultToolkit().getScreenSize();
        SearchStockFrame lf=new SearchStockFrame();
        lf.setVisible(true);
        lf.setSize(d);
    }//GEN-LAST:event_jMenuItem9ActionPerformed

    private void jMenuItem11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem11ActionPerformed
        // TODO add your handling code here:
        this.dispose();
        Dimension d=Toolkit.getDefaultToolkit().getScreenSize();

        NewPurchaseFrame nf=new NewPurchaseFrame();
        nf.setVisible(true);
        nf.setSize(d);
    }//GEN-LAST:event_jMenuItem11ActionPerformed

    private void jMenuItem16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem16ActionPerformed
        // TODO add your handling code here:
        this.dispose();
        Dimension d=Toolkit.getDefaultToolkit().getScreenSize();

        SearchPurchaseFrame lf=new SearchPurchaseFrame();
        lf.setVisible(true);
        lf.setSize(d);
    }//GEN-LAST:event_jMenuItem16ActionPerformed

    private void jMenuItem17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem17ActionPerformed
        // TODO add your handling code here:
        this.dispose();
        Dimension d = Toolkit.getDefaultToolkit().getScreenSize();

        PurchasePaymentFrame lf = new PurchasePaymentFrame();
        lf.setVisible(true);
        lf.setSize(d);
    }//GEN-LAST:event_jMenuItem17ActionPerformed

    private void jMenuItem18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem18ActionPerformed
        // TODO add your handling code here:
        this.dispose();
        Dimension d=Toolkit.getDefaultToolkit().getScreenSize();

        AdvancePaymentFrame lf=new AdvancePaymentFrame();
        lf.setVisible(true);
        lf.setSize(d);
    }//GEN-LAST:event_jMenuItem18ActionPerformed

    private void jMenuItem19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem19ActionPerformed
        // TODO add your handling code here:
        this.dispose();
        Dimension d=Toolkit.getDefaultToolkit().getScreenSize();

        NewSaleFrame lf=new NewSaleFrame();
        lf.setVisible(true);
        lf.setSize(d);
    }//GEN-LAST:event_jMenuItem19ActionPerformed

    private void jMenuItem20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem20ActionPerformed
        // TODO add your handling code here:
        this.dispose();
        Dimension d=Toolkit.getDefaultToolkit().getScreenSize();

        SearchSaleFrame lf=new SearchSaleFrame();
        lf.setVisible(true);
        lf.setSize(d);
    }//GEN-LAST:event_jMenuItem20ActionPerformed

    private void jMenuItem12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem12ActionPerformed

        new ManageProfileDBOperation().insertStaffLoginDetails(LoginFrame.uname, LoginFrame.logindatetime, logoutdatetime);
        this.dispose();
        Dimension d = Toolkit.getDefaultToolkit().getScreenSize();
        LoginFrame af = new LoginFrame();
        af.setVisible(true);
        af.setSize(d);        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem12ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditItemFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditItemFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditItemFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditItemFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EditItemFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    public static javax.swing.JComboBox<String> jComboBox1;
    public static javax.swing.JComboBox jComboBox2;
    public static javax.swing.JComboBox jComboBox3;
    private javax.swing.JLabel jLabel1;
    public static javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    public static javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem11;
    private javax.swing.JMenuItem jMenuItem12;
    private javax.swing.JMenuItem jMenuItem15;
    private javax.swing.JMenuItem jMenuItem16;
    private javax.swing.JMenuItem jMenuItem17;
    private javax.swing.JMenuItem jMenuItem18;
    private javax.swing.JMenuItem jMenuItem19;
    private javax.swing.JMenuItem jMenuItem20;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JPanel jPanel1;
    public static javax.swing.JRadioButton jRadioButton1;
    public static javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JScrollPane jScrollPane1;
    public static javax.swing.JTextArea jTextArea1;
    public static javax.swing.JTextField jTextField1;
    public static javax.swing.JTextField jTextField4;
    public static javax.swing.JTextField jTextField5;
    public static javax.swing.JTextField jTextField6;
    // End of variables declaration//GEN-END:variables
}
